// Read assets/inter-*.woff2 and emit src/styles/font-data.ts with each font
// inlined as a base64 data: URL. This lets the final bundle ship as a single
// .js file via HACS (no zip_release tricks), at the cost of ~760KB of base64
// strings inside the bundle. Trade-off accepted because HACS in zip_release
// mode misregisters the Lovelace resource (zip path as JS module).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const weights = {
  light: 300,
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
};

const out = [
  "// AUTO-GENERATED by scripts/embed-fonts.mjs — do not edit by hand.",
  "// Regenerate with `npm run embed-fonts` (run automatically by `npm run build`).",
  "",
  "export const INTER_FONTS_CSS = `",
];

let totalBytes = 0;
for (const [name, weight] of Object.entries(weights)) {
  const file = join(root, `assets/inter-${name}.woff2`);
  const buf = readFileSync(file);
  const b64 = buf.toString("base64");
  totalBytes += buf.byteLength;
  out.push(`@font-face {`);
  out.push(`  font-family: 'Inter';`);
  out.push(`  font-style: normal;`);
  out.push(`  font-weight: ${weight};`);
  out.push(`  font-display: block;`);
  out.push(`  src: url(data:font/woff2;base64,${b64}) format('woff2');`);
  out.push(`}`);
}

out.push("`;");
out.push("");

const target = join(root, "src/styles/font-data.ts");
writeFileSync(target, out.join("\n"));

const kb = (n) => `${(n / 1024).toFixed(1)}KB`;
console.log(
  `Embedded 5 Inter weights (${kb(totalBytes)} raw → ~${kb(totalBytes * 4 / 3)} base64) into ${target}`,
);
